[package]
name = "webapp-companion-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
grpc-web-client = "0.1.2"
tonic = "0.7.1"
wasm-bindgen = "0.2.80"
prost = "0.10"

[build-dependencies]
tonic-build = "0.7.0"
